# Generated by Django 4.0.4 on 2023-05-16 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, default='', max_length=200)),
                ('responsavel', models.CharField(blank=True, default='', max_length=250)),
                ('nivel', models.IntegerField(choices=[(1, 1), (3, 3), (5, 5), (8, 8)])),
                ('situacao', models.CharField(max_length=12)),
                ('prioridade', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
